apiVersion: apps/v1
kind: Deployment
metadata:
    name: dispatcher-service
    labels:
        app: dispatcher-service
    annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9003"
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dispatcher-service
    template:
        metadata:
            name: dispatcher-service
            labels:
                app: dispatcher-service
        spec:
            containers:
                -   name: dispatcher-service
                    image: dispatcher-service
                    imagePullPolicy: IfNotPresent
                    livenessProbe:
                        httpGet:
                            path: /actuator/health/liveness
                            port: 9003
                        initialDelaySeconds: 10
                        periodSeconds: 5
                    readinessProbe:
                        httpGet:
                            port: 9003
                            path: /actuator/health/readiness
                        initialDelaySeconds: 5
                        periodSeconds: 20
                    lifecycle:
                        preStop:
                            exec:
                                command: [ "sh", "-c", "sleep 5" ]
                    ports:
                        -   containerPort: 9003
                    volumeMounts:
                        -   name: dispatcher-config-volume
                            mountPath: /workspace/config
            volumes:
                -   name: dispatcher-config-volume
                    configMap:
                        name: dispatcher-config
